
platform :ios, ‘9.0’
target “AppFrame” do
pod 'SDAutoLayout', '~> 1.52'
pod 'MJRefresh', '~> 3.1.0'
pod 'UIActivityIndicator-for-SDWebImage', '~> 1.2'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'Lwt_Networking', '~> 1.0.1'
pod 'Lwt_ActionSheet', '~> 1.0.1'
end

